server:
  port: 8082

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: c210073b-f73e-478e-a794-3750c215ee68
        group: MY_GROUP
      config:
        enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          # 全局超时配置
          default:
            # 网络连接阶段1秒超时
            connectTimeout: 1000
            # 服务请求响应阶段5秒超时
            readTimeout: 3000
          # 针对某个特定服务的超时配置
          service-provider:
            connectTimeout: 1000
            readTimeout: 2000


logging:
  level:
    com.yangtao.service.PersonService: debug