server:
  port: 9000

spring:
  cloud:
    nacos:
      config:
        enabled: false
      server-addr: localhost:8848
      username: nacos
      password: nacos
  profiles:
    active: globalfilters

  data:
    redis:
      host: localhost
  application:
    name: gateway-client