server:
  port: 9000

spring:
  cloud:
    nacos:
      config:
        enabled: false
      server-addr: localhost:8848
      username: nacos
      password: nacos
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods:
#              - GET
#              - POST

  profiles:
    active: global

  data:
    redis:
      host: localhost
  application:
    name: gateway-client