spring:
  cloud:
    gateway:
      routes:
        - id: header-route
          uri: http://localhost:8081/
          predicates:
            - Path=/test/header
          filters:
            - AddRequestHeader=x-trace-id,xxxyyyzzz
        - id: param-route
          uri: http://localhost:8081/
          predicates:
            - Path=/test/params
          filters:
            - AddRequestParameter=kante,xxxx
        - id: fallback-route
          uri: http://localhost:8081/
          predicates:
            - Path=/test/fallback
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fb
        - id: limit-route
          uri: http://localhost:8081/
          predicates:
            - Path=/test/limit
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@useKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1

