server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        # nacos客户端向服务端发送心跳的时间间隔，单位是ms
        heart-beat-interval: 5000
        # 服务端没有接收到客户端心跳请求就设为不健康的时间间隔，默认是15s
        heart-beat-timeout: 20000
        # 命名空间ID
        namespace: c210073b-f73e-478e-a794-3750c215ee68
        # group 同一个group内 才可以进行服务调用
        group: MY_GROUP
      config:
        file-extension: yaml
        prefix: application
        group: DEFAULT_GROUP

      server-addr: localhost:8848
      username: nacos
      password: nacos
  profiles:
    active: dev
  application:
    # 服务注册到nacos上的名称
    name: service-provider

  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}